FORMAT: 1A
HOST: https://cgfms-dev.central.co.th/service-gateway

# Order Status

## Event
### Event: OrderStatusUpdated

**Description:** This event will be send after call api update order status.

**Payload**:
```json
{
    "sourceOrderId": "{source_order_id}"
}
```

## All Status

### Saga Status
| **Status** | **Remark** |
|------------|------------|
| STARTED | Initial saga transaction |
| PROCESSING | processing logic |
| SUCCEEDED | process is success |
| COMPENSATED | process isn't success |

### Outbox status
| **Status** | **Remark** |
|------------|------------|
| STARTED | Initial outbox |
| COMPLETED | Send event to broker is completed |
| FAILED | Send event failed |

## Group Outbox Api

### Trigger publish event payload [/order-service/api/outbox/publish]

#### Trigger publish event [GET]

**Process Instruction**
- Query outbox from database
- If have data, publish event payload to Message Broker
- Update saga status follow result from publish message

+ Request (application/json)

    + Headers

        Authorization: Bearer {access-token}

+ Response 204

+ Response 500 (application/json)
    + Attributes (InternalError Base)

# Data Structures

## BadRequest Base (object)
+ statusCode: 400 (string)

    HttpStatusCode

+ statusDesc: Invalid content type (string)

    A message validate.

## NotFound Base (object)
+ statusCode: 404 (string)

    HttpStatusCode

+ statusDesc: File not found (string)

    A data is missing in system.

## InternalError Base (object)
+ statusCode: 500 (string)

    HttpStatusCode

+ statusDesc: Null Referenece Exception (string)

    A exception message.