FORMAT: 1A
HOST: https://cgfms-dev.central.co.th/service-gateway

# Order Status

**EventName:** *OrderStatusUpdated*

### Saga Status
| **Status** | **Remark** |
|------------|------------|
| STARTED | Initial saga transaction |
| PROCESSING | processing logic |
| SUCCEEDED | process is success |
| COMPENSATED | process isn't success |

### Domain status
| **Status** | **Remark** |
|------------|------------|
| PROCESSING | after process update order status is completed |
| COMPLETED | compute status aggregate completed |
| INCOMPLETED | status target out of spec (May not be used.) |
| FAILED | process exception |

### Outbox status
| **Status** | **Remark** |
|------------|------------|
| STARTED | Initial outbox |
| COMPLETED | Send event to broker is completed |
| FAILED | Send event failed |

## Group Product Api

### Trigger process product master [/product-service/api/product/importFileMaster]

#### Trigger product master [POST]

**Validation Criteria**
- [x] Check `fileId` isn't empty.

**Process Instruction**
- Create background thread for execute [Function Process File](#header-function-process-product-master)

+ Request (application/json)

    + Headers

        Authorization: Bearer {access-token}
    
    + Body

        {
            "fileId": "w143kxnu.idj"
        }

+ Response 204

+ Response 500 (application/json)
    + Attributes (InternalError Base)

# Data Structures

## BadRequest Base (object)
+ statusCode: 400 (string)

    HttpStatusCode

+ statusDesc: Invalid content type (string)

    A message validate.

## NotFound Base (object)
+ statusCode: 404 (string)

    HttpStatusCode

+ statusDesc: File not found (string)

    A data is missing in system.

## InternalError Base (object)
+ statusCode: 500 (string)

    HttpStatusCode

+ statusDesc: Null Referenece Exception (string)

    A exception message.