FORMAT: 1A
HOST: http://localhost

# CRL API
An API for import data from file

# Introduction

## About

### File

#### File Status
| **Status** | **Description**
|------------|-----------------
| New | Order
| RECEIVED | Order accepted

# Reference

## Group Data Api
This section groups CRL service

### Import [/domain-data/import]

#### Import file data [POST]
Use this endpoint to import file, by type of file is `.csv`


+ Request (multipart/form-data; boundary=---BOUNDARY)

    + Headers

        Authorization: Bearer {access-token}
    
    + Body

        -----BOUNDARY
        Content-Disposition: form-data; name="file"; fileName="sourceData.csv"
        -----BOUNDARY
+ Response 204


#### Re-process [/domain-data/{fileId}]

+ Parameters
    + fileId (string)
    
        The ID of file

#### Re-run process file [POST]
Re-run process file by `fileId`

+ Headers

    Authorization: B

+ Response 204

## Group FileManagement Api
This section group filemanagement service

### Upload [/filemanagement/uploadStream/directory/{directory}/fileName/{fileName}]

#### Upload file to blob [POST]
Use this endpoint to upload file into blob storage.

+ Parameters
    + directory (string)
    
        This field is directory name of blob.
    
    + fileName (string)

        This field is filename.

+ Request (application/octet-stream)

    + Headers

        Authorization: Bearer {access-token}
    
    + Body

        Binary Stream

